version: '3.8'

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: my-web-chess-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ../backend/models:/app/models

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    image: my-web-chess-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ../frontend:/app
      - /app/node_modules
    depends_on:
      - backend